apiVersion: v1
data:
  HTTPD_SSL_KEY: {{ include "dispatcher-ssl" . | b64enc | quote }}
  HTTPD_SSL_KEY_PASS: {{ required "Please fill in dispatcherSslKeyPass in values.yaml" .Values.secrets.dispatcherSslKeyPass | quote }}
  NSS_SDB_USE_CACHE: "no"
  PORTAL_SUBDOMAIN: {{ required "Please fill in domain in values.yaml" .Values.user.domain | quote }}
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  TSSG_PUBLIC_HOST: {{ include "tssg-public-host" . | quote }}
  USE_PROXY_PROTOCOL: "false"
kind: ConfigMap
metadata:
  labels:
    name: dispatcher
  name: dispatcher-config