{{- if .Values.user.analyticsEnabled -}}
apiVersion: v1
data:
  SERVICE_NAME: minio
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio123
kind: ConfigMap
metadata:
  labels:
    name: minio
  name: minio-config
{{- end }}