apiVersion: v1
data:
  ENTERPRISE_DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  ENTERPRISE_DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  ENTERPRISE_DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | quote }}
  ENTERPRISE_DATABASE_PORT: {{ include "database-port" . | quote }}
  ENTERPRISE_DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  ENTERPRISE_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | quote }}
  GATEWAY_PK: {{ include "pssg-ssl" . | b64enc | quote }}
  GATEWAY_PK_PASS: {{ required "Please fill in pssgSslKeyPass in values.yaml" .Values.secrets.pssgSslKeyPass | quote }}
  GATEWAY_USERNAME: admin
  HELP_BASE_URL: {{ include "portal.help.page" . | quote }}
  JAVA_OPTIONS: -Xms2048m -Xmx2048m
  NSS_SDB_USE_CACHE: "no"
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.config.password | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.config.username | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.config.cookie | quote }}
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: {{ .Values.rabbitmq.config.port | quote }}
  RBAC_DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  RBAC_DATABASE_NAME: {{ include "rbac-db-name" . | quote }}
  RBAC_DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | quote }}
  RBAC_DATABASE_PORT: {{ include "database-port" . | quote }}
  RBAC_DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  RBAC_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | quote }}
  SEARCH_DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  SEARCH_DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  SEARCH_DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | quote }}
  SEARCH_DATABASE_PORT: {{ include "database-port" . | quote }}
  SEARCH_DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  SEARCH_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | quote }}
  PAPI_PASSWORD: {{ .Values.user.papiPassword | quote }}
  PAPI_USERNAME: {{ .Values.user.papiUsername | quote }}
  PAPI_PUBLIC_HOST: {{ include "tssg-public-host" . | quote }}
  PAPI_INGRESS_TENANT: {{ include "default-tenant-id" . | quote }}
  TSSG_TENANT_ID: {{ include "default-tenant-id" . | quote }}
  {{- if .Values.user.hostnameWhitelist }}
  HOSTNAME_WHITELIST: {{ .Values.user.hostnameWhitelist}}
  {{- end }}
  {{- if and .Values.user.analyticsEnabled  .Values.user.aggregationEnabled }}
  AGGR_ENABLED: {{ required "Please fill in the aggregationEnabled in values.yaml" .Values.user.aggregationEnabled | quote }}
  {{- end}}
kind: ConfigMap
metadata:
  labels:
    name: portal-enterprise
  name: portal-enterprise-config