{{- if .Values.user.telemetry.telemetry_proxy_url }}
apiVersion: v1
kind: Secret
metadata:
  name: portal-data-secret
labels:
    name: portal-data
type: Opaque
data:
  TELEMETRY_PROXY_USERNAME: {{ .Values.user.telemetry.telemetry_proxy_username | b64enc | quote }}
  TELEMETRY_PROXY_PASSWORD: {{ .Values.user.telemetry.telemetry_proxy_password | b64enc | quote }}
{{- end }}
